version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres_db
    links:
      - postgres_db:database
  postgres_db:
    image: "postgres:14.4"
    restart: always
    environment:
      POSTGRES_DB: cleaning_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password