version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres_db
    links:
      - postgres_db:database
    env_file:
      .env
  postgres_db:
    image: "postgres:14.4"
    restart: always
    env_file:
      .env